# Site settings
author: Victor Plushko
title: 
header-img: img/home-bg.png
email: vicplushko33@gmail.com
copyright_name: Victor Plushko
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  VicPlushko

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
